;
[Paperres_Config]
pdf_folder_path = pdf
paperrec_folder_path = paperrec
tmp_folder_path = tmp
image_prefix = url-minio-jpg

;
[Minio_Config]
minio_access_key = Pqj3BynzRwemHsenKqc6
minio_secret_key = SUWRaRiQyXSFD0ykjGsaqP4hNbw1mmqjENXaKVbl
host = 10.8.29.28
port = 9001
https = False
minio_bucket_name = paperrecimage
;
[Log]
host = 10.8.29.27
port = 12201
level = DEBUG
islog = True

[Redis_Config]
host = 10.8.29.28
port = 6379
password = jhkdjhkjdhsIUTYURTU_3XrJeJ
db = 0